const TicketTypes = {
  GET_TICKETS_START: "GET_TICKETS_START",
  GET_TICKETS_SUCCESS: "GET_TICKETS_SUCCESS",
  GET_TICKETS_FAILURE: "GET_TICKETS_FAILURE",

  UPDATE_TICKET_START: "UPDATE_TICKET_START",
  UPDATE_TICKET_SUCCESS: "UPDATE_TICKET_SUCCESS",
  UPDATE_TICKET_FAILURE: "UPDATE_TICKET_FAILURE",

  ADD_TICKET_START: "ADD_TICKET_START",
  ADD_TICKET_SUCCESS: "ADD_TICKET_SUCCESS",
  ADD_TICKET_FAILURE: "ADD_TICKET_FAILURE",
};

export default TicketTypes;
