const BoardActions = {
  GET_BOARDS_START: "GET_BOARDS_START",
  GET_BOARDS_SUCCESS: "GET_BOARDS_SUCCESS",
  GET_BOARDS_FAILURE: "GET_BOARDS_FAILURE",

  ADD_BOARD_START: "ADD_BOARD_START",
  ADD_BOARD_SUCCESS: "ADD_BOARD_SUCCESS",
  ADD_BOARD_FAILURE: "ADD_BOARD_FAILURE",

  GET_BOARD_LINES: "GET_BOARD_LINES",
  GET_BOARD_SUCCESS: "GET_BOARD_SUCCESS",
  GET_BOARD_FAILURE: "GET_BOARD_FAILURE",

  GENERATE_HASHED_BOARD_ID_START: "ENERATE_HASHED_BOARD_ID_START",
  GENERATE_HASHED_BOARD_ID_SUCCESS: "ENERATE_HASHED_BOARD_ID_SUCCESS",
  GENERATE_HASHED_BOARD_ID_FAILURE: "ENERATE_HASHED_BOARD_ID_FAILURE",

  JOIN_BOARD_START: "JOIN_BOARD_START",
  JOIN_BOARD_SUCCESS: "JOIN_BOARD_SUCCES",
  JOIN_BOARD_FAILURE: "JOIN_BOARD_FAILURE",

  FETCH_BOARD_MEMBERS_START: "FETCH_BOARD_MEMBERS_START",
  FETCH_BOARD_MEMBERS_SUCCESS: "FETCH_BOARD_MEMBERS_SUCCESS",
  FETCH_BOARD_MEMBERS_FAILURE: "FETCH_BOARD_MEMBERS_FAILURE",
};

export default BoardActions;
