const LanesActions = {
  GET_LANES_START: "GET_LANES_START",
  GET_LANES_SUCCESS: "GET_LANES_SUCCESS",
  GET_LANES_FAILURE: "GET_LANES_FAILURE",

  ADD_LANE_START: "ADD_LANE_START",
  ADD_LANE_SUCCESS: "ADD_LANE_SUCCESS",
  ADD_LANE_FAILURE: "ADD_LANE_FAILURE",

  DELETE_LANE_START: "DELETE_LANE_START",
  DELETE_LANE_SUCCESS: "DELETE_LANE_SUCCESS",
  DELETE_LANE_FAILURE: "DELETE_LANE_FAILURE",
};

export default LanesActions;
