const UserTypes = {
  SIGN_IN: "SIGN_IN",

  SIGN_OUT_START: "SIGN_OUT_START",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",

  GET_TOKEN_START: "GET_TOKEN_START",
  GET_TOKEN_SUCCESS: "GET_TOKEN_SUCCESS",
  GET_TOKEN_FAILURE: "GET_TOKEN_FAILURE",

  REMOVE_TOKEN_START: "REMOVE_TOKEN_START",
  REMOVE_TOKEN_SUCCESS: "REMOVE_TOKEN_SUCCESS",
  REMOVE_TOKEN_FAILURE: "REMOVE_TOKEN_FAILURE",

  SET_LANDING_PAGE: "SET_LANDING_PAGE",
  UNSET_LANDING_PAGE: "UNSET_LANDING_PAGE",
};

export default UserTypes;
